### ISSUE TITLE
Add a PR template with a checklist

### ISSUE THREAD

**Issue by ttarczynski** [ContainerSolutions/terraform-examples#60]
It should list what is required for the PR.
Something like:

# General contribution criteria

Please have a look at our contribution guidelines: ...
Particularly the sections about the:
- contribution workflow
- Principles
- Conventions
- add CHANGELOG.md entry
- ...

The following short checklist should be used to make sure your PR is of good
quality, and can be merged easily:
- [ ] does it follow project Conventions?
- [ ] does it follow project Principles?
- [ ] do all the checks pass?
- [ ] if it resolves an issue;
      is a reference (i.e. #1) to this issue included?
